### ISSUE TITLE
How can I specify the direct mode at connectionMode?

### ISSUE THREAD

**Issue by kaneshuzou** [Azure/azure-documentdb-js#21]
We have a performance problem on registering 2,000 data.
So, I've tried to connect by direct mode to document DB.

But I could not find any definition for direct mode in documents.js.
Only gateway mode seems to be defined.
```
ConnectionMode: Object.freeze({
    Gateway: 0
}),
```

And 'ConnectionMode' not seems to be referenced at any files.
Can I specify the connectionMode or not?

**Comment by kaneshuzou** [comment]
sorry, this is just a question. so, I'll ask this on other QA site.

**Comment by rnagpal** [comment]
@kaneshuzou JavaScript client doesn't supports Direct mode and only works in Gateway mode.

**Comment by kaneshuzou** [comment]
thanks, I'll take the other solution.
